# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 23:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('hireable', models.BooleanField(default=True)),
                ('travel_radius', models.IntegerField(blank=True, default=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('camera_type', models.CharField(blank=True, choices=[('nikon', 'Nikon'), ('canon', 'Canon'), ('iPhone', 'iPhone')], max_length=255, null=True)),
                ('photography_type', models.CharField(blank=True, choices=[('LA', 'Landscape'), ('WD', 'Weddings'), ('AN', 'Animals'), ('PT', 'Portraits'), ('UR', 'Urban'), ('FA', 'Fashion'), ('TR', 'Travel'), ('WA', 'Water')], max_length=2, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
