# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imager_profile', '0002_auto_20170117_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('data_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('published', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('public', 'Public')], max_length=255)),
                ('cover_image', models.ImageField(upload_to='')),
                ('owner', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='imager_profile.ImagerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('data_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('published', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('public', 'Public')], max_length=255)),
                ('image', models.ImageField(upload_to='media')),
                ('owner', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='imager_profile.ImagerProfile')),
            ],
        ),
    ]
