# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ManyToManyField(to='imager_images.Image'),
        ),
    ]
