# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0004_auto_20170119_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='image',
            new_name='images',
        ),
        migrations.AlterField(
            model_name='album',
            name='published',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('shared', 'Shared'), ('public', 'Public')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='published',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('shared', 'Shared'), ('public', 'Public')], max_length=255, null=True),
        ),
    ]
