# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0005_auto_20170122_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='data_modified',
            new_name='date_modified',
        ),
    ]
